# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: 2.7.18
            PLONE_VERSION: 4.3
            continue-on-error: false
          - python: 3.8.16
            PLONE_VERSION: 5.2
            continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libjpeg-dev libbz2-dev
      - name: Set up pyenv and Python
        uses: "gabrielfalcao/pyenv-action@v18"
        with:
          default: "${{ matrix.python }}"
          command: pyenv -v
      - name: Setup Env
        run: |
          mkdir -p buildout-cache/{eggs,downloads}
          pip install -r requirements.txt coverage==5.3.1 wheel
      - name: Cache eggs
        uses: actions/cache@v4
        env:
          cache-name: cache-eggs
        with:
          path: ~/buildout-cache/eggs
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.PLONE_VERSION }}
      - name: buildout
        run: |
          sed -ie "s#plone-4.3#plone-${{matrix.PLONE_VERSION}}#" buildout.cfg 
          buildout -c ci.cfg annotate
          buildout -c ci.cfg
      - name: test
        run: |
          bin/test -t !robot
  coverage:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: 2.7.18
            PLONE_VERSION: 4
            continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up pyenv and Python
        uses: "gabrielfalcao/pyenv-action@v18"
        with:
          default: "${{ matrix.python }}"
          command: pyenv -v
      - name: Setup Env
        run: |
          mkdir -p buildout-cache/{eggs,downloads}
          pip install -r requirements.txt coverage==5.3.1 wheel
      - name: Cache eggs
        uses: actions/cache@v4
        env:
          cache-name: cache-eggs
        with:
          path: ~/buildout-cache/eggs
          key: ${{ runner.os }}-build-${{ env.cache-name }}-coverage-${{ matrix.PLONE_VERSION }}
      - name: buildout
        run: |
          buildout -c ci.cfg
      - name: code-analysis
        run: |
          bin/code-analysis
      - name: test coverage
        run: |
          bin/coverage run bin/test -t !robot
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Coveralls
        run: |
          pip3 install -U pip setuptools --no-cache-dir
          pip3 install -U "coveralls>=3.0.0" coverage==5.3.1 --no-cache-dir
      - name: Publish to Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls --service=github
